version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          args: pre-commit
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pre-commit run --all-files
          name: Test
workflows:
  main:
    jobs:
      - test
